CREATE TABLE `tr_pr_non_po` (
  `id` int NOT NULL AUTO_INCREMENT,
  `no_non_po` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `id_pr` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `no_pr` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `jenis_pr` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `id_pic` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `nm_pic` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `total_pr` decimal(20,2) NOT NULL DEFAULT '0.00',
  `sts` enum('0','1','2','3') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '0',
  `reject_reason` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `approved_by` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `approved_date` datetime DEFAULT NULL,
  `rejected_by` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `rejected_date` datetime DEFAULT NULL,
  `created_by` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `created_date` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=137 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `material_planning_base_on_produksi` (
  `id` int NOT NULL AUTO_INCREMENT,
  `so_number` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `no_pr` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `category` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'base on production',
  `tgl_so` date DEFAULT NULL,
  `po_number` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `po_date` date DEFAULT NULL,
  `id_customer` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `project` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `qty_order` double(16,5) DEFAULT NULL,
  `qty_use_stok` double(16,5) DEFAULT NULL,
  `qty_propose` double(16,5) DEFAULT NULL,
  `tgl_dibutuhkan` date DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  `deleted_date` datetime DEFAULT NULL,
  `booking_by` int DEFAULT NULL,
  `booking_date` datetime DEFAULT NULL,
  `sts_req_app` int NOT NULL,
  `app_req` int NOT NULL,
  `sts_po_req` int NOT NULL,
  `app_po_req` int NOT NULL,
  `no_rev` int NOT NULL,
  `reject_status` int NOT NULL,
  `reject_reason` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `metode_pembelian` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `app_1` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `app_2` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `app_3` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `sts_reject1` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `sts_reject2` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `sts_reject3` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `app_1_by` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `app_1_date` datetime DEFAULT NULL,
  `app_2_by` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `app_2_date` datetime DEFAULT NULL,
  `app_3_by` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `app_3_date` datetime DEFAULT NULL,
  `sts_reject1_by` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `sts_reject1_date` datetime DEFAULT NULL,
  `sts_reject2_by` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `sts_reject2_date` datetime DEFAULT NULL,
  `sts_reject3_by` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `sts_reject3_date` datetime DEFAULT NULL,
  `reject_reason1` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `reject_reason2` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `reject_reason3` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `keterangan_1` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `keterangan_2` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `keterangan_3` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `app_post` varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `rejected` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `sts_app` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `tingkat_pr` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `close_pr` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `close_pr_desc` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `nilai_budget` decimal(20,2) NOT NULL DEFAULT '0.00',
  `nilai_pengajuan` decimal(20,2) NOT NULL DEFAULT '0.00',
  `current_stage_no` int DEFAULT '1',
  `current_status` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'active',
  `revision_no` int DEFAULT '1',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

CREATE TABLE `material_planning_base_on_produksi_detail` (
  `id` int NOT NULL AUTO_INCREMENT,
  `so_number` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `id_material` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `qty_order` double(16,5) DEFAULT NULL,
  `stock_free` double(16,5) DEFAULT NULL,
  `use_stock` double(16,5) DEFAULT NULL,
  `min_stock` double(9,2) DEFAULT NULL,
  `max_stock` double(9,2) DEFAULT NULL,
  `propose_purchase` double(16,5) DEFAULT NULL,
  `propose_rev` double(16,5) DEFAULT NULL,
  `status_app` enum('Y','N','D') CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'N',
  `app_by` int DEFAULT NULL,
  `app_date` datetime DEFAULT NULL,
  `note` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `kasbon_created` int DEFAULT NULL,
  `price_ref` decimal(20,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=226 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

CREATE TABLE `accessories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_category` int DEFAULT NULL,
  `id_stock` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `stock_name` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `trade_name` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `brand` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `spec` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `id_unit_gudang` int DEFAULT NULL,
  `konversi` double(9,2) NOT NULL DEFAULT '1.00',
  `id_unit` int DEFAULT NULL,
  `min_stok` double(16,4) DEFAULT NULL,
  `max_stok` double(16,4) DEFAULT NULL,
  `min_order` decimal(20,2) NOT NULL DEFAULT '0.00',
  `status` enum('1','0') CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT '1',
  `created_by` int DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  `deleted_date` datetime DEFAULT NULL,
  `price_ref` double(16,6) DEFAULT NULL,
  `price_ref_high` double(16,6) DEFAULT NULL,
  `price_ref_high_usd` double(16,6) DEFAULT NULL,
  `price_ref_usd` double(16,6) DEFAULT NULL,
  `price_ref_date` date DEFAULT NULL,
  `price_ref_expired` int DEFAULT NULL,
  `note` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `upload_file` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `status_app` enum('Y','N') CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'N',
  `app_by` int DEFAULT NULL,
  `app_date` datetime DEFAULT NULL,
  `price_ref_new` double(16,6) DEFAULT NULL,
  `price_ref_high_new` double(16,6) DEFAULT NULL,
  `price_ref_high_new_usd` double(16,6) DEFAULT NULL,
  `price_ref_new_usd` double(16,6) DEFAULT NULL,
  `price_ref_new_date` date DEFAULT NULL,
  `price_ref_new_expired` int DEFAULT NULL,
  `status_reject` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `price_ref_use` double(16,6) DEFAULT NULL,
  `price_ref_use_usd` double(16,6) DEFAULT NULL,
  `price_ref_date_use` date DEFAULT NULL,
  `price_ref_expired_use` int DEFAULT NULL,
  `id_kurs` int DEFAULT NULL,
  `kurs` decimal(16,6) DEFAULT NULL,
  `request` double(16,2) DEFAULT NULL,
  `request_pack` double(16,2) DEFAULT NULL,
  `tgl_dibutuhkan` date DEFAULT NULL,
  `spec_pr` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `info_pr` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `no_coa` varchar(100) DEFAULT NULL,
  `nm_coa` text,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=72 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

CREATE TABLE `warehouse` (
  `id` tinyint NOT NULL AUTO_INCREMENT,
  `kd_gudang` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nm_gudang` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('Y','N') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sts_ajust` enum('Y','N') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Y',
  `sts_1` enum('Y','N') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Y' COMMENT 'show list adjusment origin warehouse',
  `sts_2` enum('Y','N') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'Y' COMMENT 'show list adjusment dest warehouse',
  `urut` tinyint DEFAULT NULL,
  `urut2` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `warehouse_adjustment` (
  `id` int NOT NULL AUTO_INCREMENT,
  `kode_trans` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal` date DEFAULT NULL,
  `no_ipp` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `category` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `adjustment_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jumlah_mat` double(16,5) DEFAULT NULL,
  `jumlah_mat_packing` double(16,5) DEFAULT NULL,
  `jumlah_mat_check` double(16,5) DEFAULT NULL,
  `id_gudang_dari` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kd_gudang_dari` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_gudang_ke` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kd_gudang_ke` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `pic` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_dept` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `checked` enum('Y','N') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `checked_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `checked_date` datetime DEFAULT NULL,
  `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleted_date` datetime DEFAULT NULL,
  `inc_inv_create` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `doc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=618 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `warehouse_adjustment_detail` (
  `id` int NOT NULL AUTO_INCREMENT,
  `kode_trans` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `no_ipp` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_material` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `nm_material` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `qty_order` double(16,5) DEFAULT '0.00000',
  `qty_oke` double(16,5) DEFAULT NULL,
  `qty_rusak` double(16,5) DEFAULT '0.00000',
  `expired_date` date DEFAULT NULL,
  `keterangan` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `update_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `check_qty_oke` double(16,5) DEFAULT NULL,
  `check_qty_rusak` double(16,5) DEFAULT '0.00000',
  `check_expired_date` date DEFAULT NULL,
  `check_keterangan` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `no_ba` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_lot` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipe_po` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_po_detail` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ket_req_po` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nm_category` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`,`id_material`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=813 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `warehouse_stock` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_material` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `idmaterial` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `nm_material` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `id_category` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `nm_category` varchar(150) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `id_gudang` int DEFAULT NULL,
  `kd_gudang` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `begining` double(10,4) DEFAULT '0.0000',
  `incoming` double(10,4) DEFAULT '0.0000',
  `outgoing` double(10,4) DEFAULT '0.0000',
  `qty_stock` double(10,4) DEFAULT '0.0000',
  `qty_booking` double(10,4) DEFAULT '0.0000',
  `qty_rusak` double(10,4) DEFAULT '0.0000',
  `update_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=127 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `warehouse_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_material` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `idmaterial` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `nm_material` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `id_category` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `nm_category` varchar(150) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `id_gudang` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kd_gudang` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_gudang_dari` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kd_gudang_dari` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_gudang_ke` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kd_gudang_ke` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `incoming_awal` double(10,3) DEFAULT NULL,
  `incoming_akhir` double(10,3) DEFAULT NULL,
  `qty_stock_awal` double(10,3) DEFAULT '0.000',
  `qty_stock_akhir` double(10,3) DEFAULT NULL,
  `qty_booking_awal` double(10,3) DEFAULT '0.000',
  `qty_booking_akhir` double(10,3) DEFAULT NULL,
  `qty_rusak_awal` double(10,3) DEFAULT '0.000',
  `qty_rusak_akhir` double(10,3) DEFAULT NULL,
  `no_ipp` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jumlah_mat` double(10,3) DEFAULT NULL,
  `ket` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `tanda_terima` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `surat_jalan` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `qty_ng` decimal(20,2) DEFAULT '0.00',
  PRIMARY KEY (`id`,`id_material`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1704 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `warehouse_stock_per_day` (
  `id_material` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `nm_material` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `id_gudang` int DEFAULT NULL,
  `qty_stock` double(10,3) DEFAULT '0.000',
  `qty_booking` double(10,3) DEFAULT '0.000',
  `qty_rusak` double(10,3) DEFAULT '0.000',
  `hist_date` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tr_cost_book` (
  `id` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `id_material` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `nm_material` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `kode_produk` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `tipe_material` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `id_gudang_dari` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `nm_gudang_dari` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `id_gudang_ke` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `nm_gudang_ke` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `tgl` date NOT NULL,
  `no_transaksi` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `jenis_transaksi` text CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `qty_transaksi` decimal(20,2) NOT NULL,
  `qty` decimal(20,2) NOT NULL,
  `nilai_in` decimal(20,2) NOT NULL,
  `nilai_beli` decimal(20,2) NOT NULL,
  `costbook` decimal(20,2) NOT NULL,
  `value_transaksi` decimal(20,2) NOT NULL,
  `value_neraca` decimal(20,2) NOT NULL,
  `created_by` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `created_on` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

CREATE TABLE `price_book` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_material` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `pusat` double(16,2) DEFAULT NULL,
  `subgudang` double(16,2) DEFAULT NULL,
  `produksi` double(16,2) DEFAULT NULL,
  `price_book` double(16,2) DEFAULT NULL,
  `status` enum('Y','N') CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'Y',
  `delivery` double(16,2) DEFAULT NULL,
  `delivery_proposional` double(16,2) DEFAULT NULL,
  `incoming` double(16,2) DEFAULT NULL,
  `price` double(16,2) DEFAULT NULL,
  `updated_by` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `kode_trans` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `id_material` (`id_material`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=121 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

CREATE TABLE `ms_satuan` (
  `id` int NOT NULL AUTO_INCREMENT,
  `category` enum('unit','packing') CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT 'unit',
  `code` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `nama` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `created_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `updated_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `deleted` enum('N','Y') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'N',
  `deleted_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deleted_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

